import { SkillNode, SkillType } from '../../../types';

export const STAGE_2_SKILLS: Record<string, SkillNode> = {
    'arcaneIntellect': {
        id: 'arcaneIntellect',
        name: 'Arcane Intellect',
        description: (level) => `+${level * 3} Wisdom, +${level*20} Max Mana. Next: +3 Wis, +20 Mana.`,
        maxLevel: 5,
        cost: (level) => level + 1,
        dependencies: [],
        type: SkillType.Passive,
        position: { row: 0, col: 3 },
    },
    'manaShield': {
        id: 'manaShield',
        name: 'Mana Shield',
        description: (level) => `When hit, consume Mana to block 50% of damage.`,
        maxLevel: 1,
        cost: (level) => 2,
        dependencies: ['arcaneIntellect'],
        type: SkillType.Triggered,
        position: { row: 1, col: 3 },
    },
    'spellPower': {
        id: 'spellPower',
        name: 'Spell Power',
        description: (level) => `Magic effects deal ${level * 15}% more damage. Next: +15% damage.`,
        maxLevel: 5,
        cost: (level) => level + 2,
        dependencies: ['arcaneIntellect'],
        type: SkillType.Passive,
        position: { row: 1, col: 4 },
    },
    'elementalInfusion': {
        id: 'elementalInfusion',
        name: 'Elemental Infusion',
        description: (level) => `Active: Your next 5 ball hits apply a random elemental effect.`,
        maxLevel: 1,
        cost: (level) => 3,
        dependencies: ['manaShield'],
        type: SkillType.Active,
        position: { row: 2, col: 3 },
    },
    'runicEmpowerment': {
        id: 'runicEmpowerment',
        name: 'Runic Empowerment',
        description: (level) => `Every 5 bricks destroyed grants a random 3s buff: Haste, Power, or Shield.`,
        maxLevel: 1,
        cost: (level) => 4,
        dependencies: ['elementalInfusion'],
        type: SkillType.Passive,
        position: { row: 3, col: 3 },
    },
    'arcaneOrb': {
        id: 'arcaneOrb',
        name: 'Arcane Orb',
        description: (level) => `Active: Launch a slow magical orb that pierces all bricks, dealing damage based on Wisdom.`,
        maxLevel: 1,
        cost: (level) => 4,
        dependencies: ['spellPower'],
        type: SkillType.Active,
        position: { row: 2, col: 4 },
    },
     'masterOfElements': {
        id: 'masterOfElements',
        name: 'Master of Elements',
        description: () => `Breakthrough hits create a damaging elemental beam in the ball's direction of travel.`,
        maxLevel: 1,
        cost: () => 5,
        dependencies: ['breakthrough'],
        type: SkillType.Passive,
        position: { row: 2, col: 1 },
    },
    'timeWarp': {
        id: 'timeWarp',
        name: 'Time Warp',
        description: () => 'Ultimate: Rewind active balls to their position from 2 seconds ago. Costs 150 Mana.',
        maxLevel: 1,
        cost: () => 5,
        dependencies: ['runicEmpowerment', 'arcaneOrb'],
        type: SkillType.Active,
        position: { row: 4, col: 4 },
    },
};