import { SkillNode, SkillType } from '../../../types';

export const WORLD_4_SKILLS: Record<string, SkillNode> = {
  ingeniousMind: {
    id: 'ingeniousMind',
    name: 'Ingenious Mind',
    description: (level) => `+${level * 3} Ingenuity, +${level * 10}% XP gain from mechanicals`,
    maxLevel: 5,
    cost: (level) => 1 + level,
    dependencies: [],
    type: SkillType.Passive,
    position: { row: 0, col: 0 },
  },
  precisionTiming: {
    id: 'precisionTiming',
    name: 'Precision Timing',
    description: () => 'Perfect paddle hits (center 20%) deal double damage',
    maxLevel: 1,
    cost: () => 2,
    dependencies: ['ingeniousMind'],
    type: SkillType.Passive,
    position: { row: 0, col: 2 },
  },
  overclockSkill: {
    id: 'overclockSkill',
    name: 'Overclock',
    description: () => 'Active: All balls move faster but deal 150% damage for 5s',
    maxLevel: 1,
    cost: () => 3,
    dependencies: ['precisionTiming'],
    type: SkillType.Active,
    position: { row: 1, col: 1 },
  },
  emergencyRepair: {
    id: 'emergencyRepair',
    name: 'Emergency Repair',
    description: () => 'Triggered: At <30% HP, heal 25% max HP once per stage',
    maxLevel: 1,
    cost: () => 3,
    dependencies: ['ingeniousMind'],
    type: SkillType.Triggered,
    position: { row: 1, col: 3 },
  },
  temporalEcho: {
    id: 'temporalEcho',
    name: 'Temporal Echo',
    description: () => '20% chance to create a ghost ball that mimics next 3 bounces',
    maxLevel: 1,
    cost: () => 4,
    dependencies: ['overclockSkill'],
    type: SkillType.Passive,
    position: { row: 2, col: 1 },
  },
  steamBurst: {
    id: 'steamBurst',
    name: 'Steam Burst',
    description: () => 'Active: Paddle releases 3 projectiles upward',
    maxLevel: 1,
    cost: () => 3,
    dependencies: ['overclockSkill'],
    type: SkillType.Active,
    position: { row: 2, col: 2 },
  },
  perpetualMotion: {
    id: 'perpetualMotion',
    name: 'Perpetual Motion',
    description: () => 'Balls hitting 10+ bricks without paddle gain +25% damage',
    maxLevel: 1,
    cost: () => 4,
    dependencies: ['temporalEcho'],
    type: SkillType.Passive,
    position: { row: 3, col: 1 },
  },
  chronoBreak: {
    id: 'chronoBreak',
    name: 'Chrono Break',
    description: () => 'Ultimate: Freeze bricks for 3s; balls/paddle still move',
    maxLevel: 1,
    cost: () => 5,
    dependencies: ['perpetualMotion'],
    type: SkillType.Active,
    position: { row: 3, col: 2 },
  },
  gearShift: {
    id: 'gearShift',
    name: 'Gear Shift',
    description: (level) => `Active: Toggle between Speed Mode (+${level * 20}% ball speed) and Power Mode (+${level * 30}% damage). Cooldown: 12s.`,
    maxLevel: 3,
    cost: (level) => 2 + level,
    dependencies: ['ingeniousMind'],
    type: SkillType.Active,
    position: { row: 1, col: 0 },
  },
  clockworkPrecision: {
    id: 'clockworkPrecision',
    name: 'Clockwork Precision',
    description: (level) => `${5 + (level * 5)}% chance for ball hits to deal ${level * 50}% bonus critical damage. Perfect timing increases crit rate.`,
    maxLevel: 4,
    cost: (level) => 2 + level,
    dependencies: ['gearShift'],
    type: SkillType.Passive,
    position: { row: 2, col: 0 },
  },
  momentumGenerator: {
    id: 'momentumGenerator',
    name: 'Momentum Generator',
    description: (level) => `Ball speed increases by ${level * 3}% each consecutive hit (max 10 stacks). Paddle catches reset but grant ${level * 10}% damage boost.`,
    maxLevel: 3,
    cost: (level) => 2 + level,
    dependencies: ['emergencyRepair'],
    type: SkillType.Passive,
    position: { row: 2, col: 3 },
  },
};



