import { SkillNode, SkillType } from '../../../types';

export const WORLD_1_SKILLS: Record<string, SkillNode> = {
    'powerBoost': {
        id: 'powerBoost',
        name: 'Power Boost',
        description: (level) => `Increases Power by ${level * 2}. Next: +2 Power.`,
        maxLevel: 5,
        cost: (level) => level + 1,
        dependencies: [],
        type: SkillType.Passive,
        position: { row: 0, col: 0 },
    },
    'vitalityBoost': {
        id: 'vitalityBoost',
        name: 'Vitality Boost',
        description: (level) => `Increases max HP by ${level * 20}. Next: +20 HP.`,
        maxLevel: 5,
        cost: (level) => level + 1,
        dependencies: [],
        type: SkillType.Passive,
        position: { row: 0, col: 2 },
    },
    'ballDamageBoost': {
        id: 'ballDamageBoost',
        name: 'Ball Damage Boost',
        description: (level) => `Increases ball damage by ${level * 10}%. Next: +10% damage.`,
        maxLevel: 5,
        cost: (level) => level + 1,
        dependencies: ['powerBoost'],
        type: SkillType.Passive,
        position: { row: 1, col: 0 },
    },
    'breakthrough': {
        id: 'breakthrough',
        name: 'Breakthrough',
        description: () => 'Ball pierces destroyed bricks, carrying remaining damage to the next target.',
        maxLevel: 1,
        cost: () => 3,
        dependencies: ['ballDamageBoost'],
        type: SkillType.Passive,
        position: { row: 2, col: 0 },
    },
    'defenseBoost': {
        id: 'defenseBoost',
        name: 'Defense Boost',
        description: (level) => `Increases Defense by ${level * 1}. Next: +1 Defense.`,
        maxLevel: 5,
        cost: (level) => level + 1,
        dependencies: ['vitalityBoost'],
        type: SkillType.Passive,
        position: { row: 1, col: 2 },
    },
     'multiBallUnlock': {
        id: 'multiBallUnlock',
        name: 'Unlock Multi-Ball',
        description: () => 'Unlocks the Multi-Ball active skill. Lets you fire two extra balls.',
        maxLevel: 1,
        cost: () => 2,
        dependencies: ['breakthrough'],
        type: SkillType.Active,
        position: { row: 3, col: 0 },
    },
    'aegisParry': {
        id: 'aegisParry',
        name: 'Aegis Parry',
        description: () => 'Active: Brief parry window. If ball hits paddle during parry, it gains +100% damage, +25% speed, and pierces 1 brick. (Spacebar/Right-Click)',
        maxLevel: 1,
        cost: () => 3,
        dependencies: ['defenseBoost'],
        type: SkillType.Active,
        position: { row: 2, col: 2 },
    },
    'royalDecree': {
        id: 'royalDecree',
        name: 'Royal Decree',
        description: (level) => `Increases gold gained from bricks by ${level * 10}%. Command presence grants +${level * 5}% XP. Next: +10% gold, +5% XP.`,
        maxLevel: 3,
        cost: (level) => level + 1,
        dependencies: ['powerBoost', 'vitalityBoost'],
        type: SkillType.Passive,
        position: { row: 1, col: 1 },
    },
    'shieldWall': {
        id: 'shieldWall',
        name: 'Shield Wall',
        description: () => 'Active: Paddle width increases by 50% for 4 seconds. Grants immunity to damage during this time. Cooldown: 25s.',
        maxLevel: 1,
        cost: () => 3,
        dependencies: ['royalDecree'],
        type: SkillType.Active,
        position: { row: 2, col: 1 },
    },
    'knightsResolve': {
        id: 'knightsResolve',
        name: "Knight's Resolve",
        description: (level) => `When below 30% HP, gain +${level * 20}% damage, +${level * 10}% defense, and heal ${level * 2} HP per brick destroyed.`,
        maxLevel: 3,
        cost: (level) => 2 + level,
        dependencies: ['shieldWall'],
        type: SkillType.Passive,
        position: { row: 3, col: 1 },
    },
};


